# Generated by Django 3.0.4 on 2020-08-18 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20190217_0600'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Sản phẩm'},
        ),
    ]
