# Generated by Django 3.0.4 on 2020-08-18 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_remove_cart_session'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0002_order_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Quản lý đặt hàng'},
        ),
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Cart', verbose_name='Giỏ hàng'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Trạng thái đơn hàng'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_description',
            field=models.TextField(default='', verbose_name='Mô tả đơn hàng'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.CharField(default='', max_length=255, verbose_name='Địa chỉ giao hàng'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Khách hàng'),
        ),
    ]
